# Consider making it the same as the one in nestybox/ubuntu-jammy-docker
FROM alpine:3.19.1

RUN apk update && apk add xz curl bash shadow && apk add --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ nsjail

# install nix
RUN /bin/bash -c "sh <(curl -L https://nixos.org/nix/install) --daemon --yes" || exit 1
ENV NIX_REMOTE=daemon


# create 500 users (script taken from Piston)
RUN for i in $(seq 1001 1500); do \
      groupadd -g $i runner$i && \
      useradd -M runner$i -g $i -u $i ; \
    done

CMD ["sleep", "0"]
